apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkis-ujes-spark-enginemanager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkis-ujes-spark-enginemanager
      # release: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: linkis-ujes-spark-enginemanager
        # release: dev
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - linkis-ujes-spark-enginemanager
                      - linkis-ujes-hive-enginemanager
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node2
      containers:
        - name: linkis-ujes-spark-enginemanager
          image: 10.206.0.5/library/linkis:linkis-ujes-spark-enginemanager
          lifecycle:
            preStop:
              exec:
                command: ["sh","/opt/ihome/linkis-ujes-spark-enginemanager/bin/stop.sh"]
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 21001
          env:
            - name: eurekaurl
              value: http://10.206.0.12:20230/eureka/
            - name: EUREKA_URL
              value: http://10.206.0.12:20230/eureka/
            - name: SERVER_HEAP_SIZE
              value: 1024M
            - name: START_PORT
              value: "21001"
          volumeMounts:
            - name: linkis-ujes-spark-enginemanager-config
              mountPath: /opt/ihome/conf
      imagePullSecrets:
        - name: registry-key
      volumes:
        - name: linkis-ujes-spark-enginemanager-config
          configMap:
            name: linkis-ujes-spark-enginemanager-config