apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkis-ujes-spark-entrance-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkis-ujes-spark-entrance
      # release: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: linkis-ujes-spark-entrance
        # release: dev
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - linkis-ujes-spark-entrance
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: linkis-ujes-spark-entrance
          image: 10.206.0.5/library/linkis:linkis-ujes-spark-entrance
          lifecycle:
            preStop:
              exec:
                command: ["sh","/opt/ihome/linkis-ujes-spark-entrance/bin/stop.sh"]
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 21000
          env:
            - name: eurekaurl
              value: http://10.206.0.12:20230/eureka/
            - name: EUREKA_URL
              value: http://10.206.0.12:20230/eureka/
            - name: SERVER_HEAP_SIZE
              value: 1024M
            - name: START_PORT
              value: "21000"
          volumeMounts:
            - name: linkis-ujes-spark-entrance-config
              mountPath: /opt/ihome/conf
      imagePullSecrets:
        - name: registry-key
      volumes:
        - name: linkis-ujes-spark-entrance-config
          configMap:
            name: linkis-ujes-spark-entrance-config