#
#  Copyright 2019 WeBank
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkis-mdm-service-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkis-mdm-service-mysql
      # release: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: linkis-mdm-service-mysql
        # release: dev
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - linkis-mdm-service-mysql
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: linkis-mdm-service-mysql
        image: zhangrong1027/linkis:linkis-mdm-service-mysql
        lifecycle:
          preStop:
            exec:
              command: ["sh","/opt/ihome/linkis-mdm-service-mysql/bin/stop.sh"]
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 22004
        livenessProbe:
            tcpSocket:
              port: 22004
            initialDelaySeconds: 15
            periodSeconds: 20
        env:
          - name: eurekaurl
            value: http://10.206.0.12:20230/eureka/
          - name: EUREKA_URL
            value: http://10.206.0.12:20230/eureka/
          - name: SERVER_HEAP_SIZE
            value: 1024M
          - name: START_PORT
            value: "22004"
        volumeMounts:
          - name: linkis-mdm-service-mysql-config
            mountPath: /opt/ihome/conf
          #          - name: resultset
          #            mountPath: /opt/ihome/data
          - name: varlog
            mountPath: /opt/ihome/linkis-mdm-service-mysql/logs
      imagePullSecrets:
        - name: registry-key
      volumes:
        - name: linkis-mdm-service-mysql-config
          configMap:
            name: linkis-mdm-service-mysql-config
        #        - name: resultset
        #          nfs:
        #            path: /data/k8s
        #            server: 10.206.0.12
        - name: varlog
          hostPath:
            path: /var/log