apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkis-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkis-gateway
      # release: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  
  template:
    metadata:
      labels:
        app: linkis-gateway
        # release: dev
    spec:
      containers:
      - name: linkis-gateway
        image: zhangrong1027/linkis:linkis-gateway
        lifecycle:
            preStop:
              exec:
                command: ["sh","/opt/ihome/linkis-gateway/bin/stop.sh"]
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 14001
        env:
          - name: eurekaurl
            value: http://10.206.0.12:20230/eureka/
          - name: jvmParams
            value: -Xms1024m -Xmx1024m
          - name: containerPort
            value: "13429"
        volumeMounts:
          - name: linkis-gateway-config
            mountPath: /opt/ihome/conf
      imagePullSecrets:
        - name: registry-key
      volumes:
        - name: linkis-gateway-config
          configMap:
            name: linkis-gateway-config