apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkis-ujes-jdbcentrance-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkis-ujes-jdbcentrance
      # release: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: linkis-ujes-jdbcentrance
        # release: dev
    spec:
      containers:
      - name: linkis-ujes-jdbcentrance
        image: zhangrong1027/linkis:linkis-jdbcentrance
        lifecycle:
          preStop:
            exec:
              command: ["sh","/opt/ihome/linkis-ujes-jdbcentrance/bin/stop.sh"]
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 14004
        env:
          - name: eurekaurl
            value: http://10.206.0.12:20230/eureka/
        volumeMounts:
          - name: linkis-ujes-jdbcentrance-config
            mountPath: /opt/ihome/conf
      imagePullSecrets:
        - name: registry-key
      volumes:
        - name: linkis-ujes-jdbcentrance-config
          configMap:
            name: linkis-ujes-jdbcentrance-config